// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3d82V7UNOBMwwtC84wZ_o7rfRu86IDUs',
    appId: '1:1045697339718:web:9adb73ed42fa3cc3cc8547',
    messagingSenderId: '1045697339718',
    projectId: 'hazri-55e1f',
    authDomain: 'hazri-55e1f.firebaseapp.com',
    storageBucket: 'hazri-55e1f.appspot.com',
    measurementId: 'G-7WLLHPCGEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZW0HUYbYelgpwB0q0Du4xBhv2uSEl7eY',
    appId: '1:1045697339718:android:290e9a921c70c654cc8547',
    messagingSenderId: '1045697339718',
    projectId: 'hazri-55e1f',
    storageBucket: 'hazri-55e1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmToEi3jnK1zwvdn5fXqCNhGvz1jYqWiQ',
    appId: '1:1045697339718:ios:d05b40effac0feb7cc8547',
    messagingSenderId: '1045697339718',
    projectId: 'hazri-55e1f',
    storageBucket: 'hazri-55e1f.appspot.com',
    iosBundleId: 'com.example.hazri2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmToEi3jnK1zwvdn5fXqCNhGvz1jYqWiQ',
    appId: '1:1045697339718:ios:0e22f27071f41756cc8547',
    messagingSenderId: '1045697339718',
    projectId: 'hazri-55e1f',
    storageBucket: 'hazri-55e1f.appspot.com',
    iosBundleId: 'com.example.hazri2.RunnerTests',
  );
}
